### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by friedbizkvit** [TrySound/inferno-datagrid#1]
- [x] rows index virtualization
- [x] column resizing
- [x] column rearranging
- [x] column pinning (left/right)
- [x] rows filtering
- [x] rows sorting
- [x] row selection navigation
- [ ] ~~cell selection navigation~~

**Comment by wowDaiver** [comment]
- [ ] saveState/restoreState

**Comment by TrySound** [comment]
- [ ] percentage and optional column width with table-layout: fixed behavior
