### ISSUE TITLE
Order columns

### ISSUE THREAD

**Issue by wowDaiver** [TrySound/inferno-datagrid#2]
Смогу объяснить только на русском ))
При драге колонок, надо не менять местами, а вставлять между. А еще показывать куда вставится колонка.
Например как в phpMyAdmin
![screenshot_3](https://cloud.githubusercontent.com/assets/5978067/22738919/8dc7aaf0-ee1a-11e6-86c7-5d6ddd04b47e.png)

**Comment by TrySound** [comment]
@wowDaiver Зацени, ссылка на главной

**Comment by wowDaiver** [comment]
Гуд! Закрываю
